name: CI-CD
on:
  push:
    branches: ["main"]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Autenticando o usúario Docker HUB
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}

      - name: Construindo a imagem e enviando para o Docker HUB
        uses: docker/build-push-action@v3.0.0
        with:
          file: "./src/Dockerfile"
          context: "./src"
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USER}}/kube-news:latest
            ${{secrets.DOCKERHUB_USER}}/kube-news:${{github.run_number}}
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3

      - name: Definindo o Kube config
        uses: Azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}

      - name: Efetuando o deploy no ambiente de teste
        uses: Azure/k8s-deploy@v3.1
        with:
          images: ${{secrets.DOCKERHUB_USER}}/kube-news:${{github.run_number}}
          manifests: |
            k8s/deployment.yaml
